version: '1.0'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  mongodb:
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5673:5672
      - 15673:15672